spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankapp
      database: creditcarddb
  application:
    name: creditcard-service

server:
  port: 8085

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    com.example.mscreditcardservice: DEBUG