spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb
      database: customerdb
  application:
    name: customer-service

server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    com.example.mscustomerservice: DEBUG